### ISSUE TITLE
Previous/Next Navigation

### ISSUE THREAD

**Issue by davemacdo** [tomjn/wp-gitbook#2]
I see the note in the readme that I need to "assign a nav menu to the sidebar to use this theme". Is that different from a regular WordPress menu? I'm in WP 5.7. While I can create a menu, put pages in it, and assign it to the sidebar area of the theme, the previous/next buttons do not work. Is there a different kind of menu I need to create? Or is there a special way I need to identify my menu as the nav menu? Thanks for the theme!

**Comment by tomjn** [comment]
It's a nav menu, aka go to the menu admin page and assign a menu, there's no special menus or options to set.

**Comment by tomjn** [comment]
These are the functions that power the previous/next links https://github.com/tomjn/wp-gitbook/blob/master/functions.php#L27-L96

I can confirm it's no longer functional in the one site I use this on, but I do not know why. If you have any insights that would be a great help

**Comment by tomjn** [comment]
tracked it down to a `===` comparing `'59'` to `59`, do a `git pull` to grab the fix

**Comment by davemacdo** [comment]
Thanks!
